defmodule Wedid.Repo.Migrations.AddUserName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :name, :text
    end

    alter table(:entries) do
      modify :created_at, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:entries) do
      modify :created_at, :utc_datetime, default: nil
    end

    alter table(:users) do
      remove :name
    end
  end
end
