defmodule Wedid.Repo.Migrations.AddAccountsCoupleAndRelationshipWithUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :couple_id, :uuid
    end

    create table(:couples, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:users) do
      modify :couple_id,
             references(:couples,
               column: :id,
               name: "users_couple_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:couples) do
      add :name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:couples) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:users, "users_couple_id_fkey")

    alter table(:users) do
      modify :couple_id, :uuid
    end

    drop table(:couples)

    alter table(:users) do
      remove :couple_id
    end
  end
end
